FROM python:3.9-slim

WORKDIR /app

COPY  requirements.txt .


RUN pip install  --no-cache-dir -r requirements.txt

COPY . /app/

ENV PYTHONPATH=/app

# Lista todos os diretórios e arquivos no container para depuração
RUN ls -R /app


CMD ["python", "main.py"]