version: "3"

services:
  kafka-broker-1:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-broker-2:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-2:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=alura
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:9092,kafka-broker-2:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - kafka-net



  producer :
    container_name: producer
    build: 
     context: .
     dockerfile: Dockerfile.Producer
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    volumes:
      - ./src:/app/src
  

  consumer :
    container_name: consumer
    build: 
     context: .
     dockerfile: Dockerfile.Consumer
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    volumes:
      - ./src:/app/src

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./src/minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=kafka
      - MINIO_ROOT_PASSWORD=kafka_espetinho
      - MINIO_ACCESS_KEY=AVcyU1dIcrfI88EqIa7p      
      - MINIO_SECRET_KEY=Wf2SYhz7K7LmsjSgFVW1Bbdtclakn98ujl66AcO4       
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
